### ISSUE TITLE
Take a look at this

### ISSUE THREAD

**Issue by KOLANICH** [Flameeyes/usbmon-tools#1]
https://github.com/KOLANICH/USBPcapOdinDumper

**Comment by Flameeyes** [comment]
Neat to see something fairly similar. Unfortunately I wouldn't be able to contribute to your project due to its license.

I'll be happy to take a look if I can come up with a compatible human readable output, since I also have some scripts doing that, that I need to port to use this library before I release them.

**Comment by KOLANICH** [comment]
>I'll be happy to take a look if I can come up with a compatible human readable output

That stuff is a pipeline with pluggable stages. On that repo parsing of ODIN packets header and puting them into nicely named files were implemented. To just dump addresses one needs to throw away the latest layer and modify some methods a bit. PCap-NG KS spec is not yet fully implemented, so is not supported yet.
